dataset: /home/zuom/ppsdg/config/dataset/tabarena-polish_companies_bankruptcy.yaml
model: xgboost
target_metric: balanced_accuracy
train_override_df: /home/shared/ppsdg-data/train_and_gen/PB_tvae-1b77cc70/default-44136fa3.csv
model_params: {}
train_params: {}
eval_params: {}
data_params: {}
metrics:
- balanced_accuracy
- accuracy
- f1
