dataset: config/dataset/tabarena-taiwanese_bankruptcy_prediction.yaml
synthetic_data: /home/shared/ppsdg-data/train_and_gen/taiwan_ctgan-4d533b37/default-44136fa3.csv
metrics:
  - dcr_val_to_real_vs_synth
  - o1_estimate
