dataset: config/dataset/tabarena-taiwanese_bankruptcy_prediction.yaml
model: xgboost
target_metric: balanced_accuracy
train_override_df: /home/shared/ppsdg-data/train_and_gen/TB_tabdiff-0b834ebf/default-44136fa3.csv
model_params: {}
train_params: {}
eval_params: {}
data_params: {}
metrics:
- balanced_accuracy
