dataset: /home/zuom/ppsdg/config/dataset/tabarena-Is-this-a-good-customer.yaml
model: xgboost
target_metric: balanced_accuracy
model_params: {}
train_params: {}
eval_params: {}
data_params: {}
metrics:
- balanced_accuracy
