dataset: config/dataset/tabarena-Bank_Customer_Churn.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow10-out-3b719570/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow11-out-3bcc3664/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow12-out-b20b750d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow13-out-ab597cb9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow14-out-fa36bd8f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow15-out-e9a136ba/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow16-out-7547ef70/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow17-out-24560fb3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow18-out-6665aa10/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow19-out-d55d17d7/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow10-in-e0dc641a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow11-in-75752b02/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow12-in-83ba73e9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow13-in-fe4bb4d8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow14-in-c5cfc77d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow15-in-cf374ab4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow16-in-1e7f03c1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow17-in-c6570a65/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow18-in-39ab7729/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow19-in-8248f81f/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow0-out-731d3e72/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal3-shadow0-in-2f5eccee/default-44136fa3.csv
