dataset: config/dataset/tabarena-Bank_Customer_Churn.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow10-out-a6e6be28/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow11-out-bf59d8d3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow12-out-8cb75e1c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow13-out-42fe3dea/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow14-out-6c72d066/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow15-out-2bc50e1b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow16-out-eeecf143/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow17-out-6a261f2f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow18-out-1e7ef391/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow19-out-bd1be51d/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow10-in-95bec38f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow11-in-c8cb989e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow12-in-b4791c43/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow13-in-a5f040d5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow14-in-9d1ca94f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow15-in-735b5fb3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow16-in-9d68d40d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow17-in-92e5513a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow18-in-4da2c265/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow19-in-b41004dc/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow0-out-9b7606f6/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_tvae_bal-shadow0-in-d712d701/default-44136fa3.csv
