synthesizer: dp_ctgan
synthesizer_params:
  epsilon: 5.0
  delta: 1.0e-05
  max_grad_norm: 1.0
  use_bce_loss: false
dataset: config/dataset/tabarena-Bank_Customer_Churn.yaml
downsample_balanced: true
canary_index: 102
include_canary: false
reference_size: 2037
reference_seed: 12
sample_size: 814
sample_seed: 39
