dataset: config/dataset/tabarena-Bank_Customer_Churn.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow10-out-eee1c142/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow11-out-fa3c72b7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow12-out-b49d9ca0/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow13-out-5edf0bdb/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow14-out-d3872a70/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow15-out-8e24ba32/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow16-out-6e446831/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow17-out-dc6ccdf9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow18-out-7be0840a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow19-out-e2360359/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow10-in-3bd23567/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow11-in-d591829d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow12-in-223a8889/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow13-in-46beae88/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow14-in-c0009eb3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow15-in-6497c967/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow16-in-23cb8ab8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow17-in-ac765284/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow18-in-95c5b5b9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow19-in-3061039b/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow0-out-d707c213/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_original_bal-shadow0-in-fb611591/default-44136fa3.csv
