synthesizer: tabdiff
dataset: config/dataset/tabarena-Bank_Customer_Churn.yaml
train_params:
  steps: 300
downsample_balanced: true
canary_index: 102
include_canary: false
reference_size: 2037
reference_seed: 12
sample_size: 814
sample_seed: 32
