synthesizer: tvae
dataset: config/dataset/tabarena-Bank_Customer_Churn.yaml
downsample_balanced: true
canary_index: 101
include_canary: false
reference_size: 2037
reference_seed: 21
sample_size: 814
sample_seed: 30
