dataset: config/dataset/tabarena-bank-marketing.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow10-out-781f6942/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow11-out-878b7e86/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow12-out-406cd5b1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow13-out-41639bfe/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow14-out-47e595f6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow15-out-f6db6553/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow16-out-accca358/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow17-out-33ef5dff/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow18-out-6f3a2227/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow19-out-1eb9c8e4/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow10-in-c0f67511/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow11-in-7b319459/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow12-in-20712cd5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow13-in-d5e763a4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow14-in-46232fc3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow15-in-5e910d31/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow16-in-a8ee95e0/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow17-in-28f66f9d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow18-in-651d5abc/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow19-in-f9cd0202/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow0-out-efc5fd22/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BM_gaussian_bal3-shadow0-in-9234ead8/default-44136fa3.csv
