synthesizer: gaussian
dataset: config/dataset/tabarena-bank-marketing.yaml
downsample_balanced: true
canary_index: 100
include_canary: false
reference_size: 5289
reference_seed: 1
sample_size: 2115
sample_seed: 10
