synthesizer: tvae
dataset: config/dataset/tabarena-bank-marketing.yaml
downsample_balanced: true
canary_index: 102
include_canary: true
reference_size: 5289
reference_seed: 12
sample_size: 2115
sample_seed: 35
