synthesizer: tabdiff
dataset: config/dataset/tabarena-bank-marketing.yaml
train_params:
  steps: 300
downsample_balanced: true
canary_index: 101
include_canary: true
reference_size: 5289
reference_seed: 22
sample_size: 2115
sample_seed: 43
