synthesizer: dp_tvae
synthesizer_params:
  epsilon: 0
  delta: 1.0e-05
  max_grad_norm: 1.0
dataset: config/dataset/tabarena-credit_card_clients_default.yaml
downsample_balanced: true
canary_index: 100
include_canary: false
reference_size: 6636
reference_seed: 2
sample_size: 2654
sample_seed: 26
