dataset: config/dataset/tabarena-credit_card_clients_default.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow10-out-d5662c4c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow11-out-7d6bc2e0/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow12-out-22d3c52b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow13-out-d0aeffa3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow14-out-bc2cefaa/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow15-out-29ccdd9b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow16-out-fd11d71f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow17-out-3eab2f94/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow18-out-8a5b69e7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow19-out-b6506e17/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow10-in-16d0aee6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow11-in-41ad412e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow12-in-8fa05456/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow13-in-897532c1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow14-in-b6d60c01/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow15-in-79791f32/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow16-in-2e366183/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow17-in-1e7f2b54/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow18-in-c4bc566a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow19-in-4241d2ee/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow0-out-acc8af76/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CC_ctgan_bal3-shadow0-in-b0414aac/default-44136fa3.csv
