dataset: config/dataset/tabarena-credit-g.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow10-out-be1f0336/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow11-out-fa57a6b1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow12-out-3b6e5a7e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow13-out-d3ce06ab/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow14-out-89bcf225/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow15-out-6a0733f6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow16-out-0be3565f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow17-out-25745fd7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow18-out-e48b5b11/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow19-out-93db3e41/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow10-in-dcb12fbf/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow11-in-2d110da9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow12-in-c1a451e6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow13-in-e15f981c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow14-in-73cc288a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow15-in-ca9048fd/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow16-in-5c1dafe9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow17-in-23414862/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow18-in-9e09d279/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow19-in-df528b08/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow0-out-01581af9/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae_bal-shadow0-in-788c0c94/default-44136fa3.csv
