synthesizer: dp_ctgan
synthesizer_params:
  epsilon: 1.0
  delta: 1.0e-05
  max_grad_norm: 1.0
  use_bce_loss: false
dataset: config/dataset/tabarena-credit-g.yaml
downsample_balanced: true
canary_index: 100
include_canary: false
reference_size: 300
reference_seed: 2
sample_size: 120
sample_seed: 27
