dataset: config/dataset/tabarena-credit-g.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow10-out-3920cd78/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow11-out-82896c49/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow12-out-a3431963/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow13-out-1705d700/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow14-out-c28296d4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow15-out-f370f660/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow16-out-c518be9e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow17-out-4c2a76c4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow18-out-cea4c7e6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow19-out-2a99dd1e/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow10-in-345da1e9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow11-in-00736ac0/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow12-in-c4a99ed7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow13-in-5e529265/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow14-in-8847011e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow15-in-4a508f1c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow16-in-98092acb/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow17-in-5f2c5227/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow18-in-697ae3cf/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow19-in-0b24254e/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow0-out-275b169d/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_ctgan_bal3-shadow0-in-567d60d6/default-44136fa3.csv
