dataset: config/dataset/tabarena-GiveMeSomeCredit.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow10-out-2a8785bf/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow11-out-c00ec8d8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow12-out-aec4c35b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow13-out-2b5cabfc/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow14-out-a9ba51cd/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow15-out-6d30e4a9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow16-out-703bdc7f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow17-out-52971f54/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow18-out-0e9f3de0/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow19-out-4d5a1260/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow10-in-b653402c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow11-in-0d82f1d5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow12-in-0ad18b72/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow13-in-f11eb17a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow14-in-0f35e69f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow15-in-1067e27a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow16-in-d61a8027/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow17-in-a6af7d7b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow18-in-f6426ff1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow19-in-26f04e2c/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow0-out-55cf5dfd/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_0.1dp_ctgan_wgan_bal3-shadow0-in-b1fd0ee6/default-44136fa3.csv
