dataset: config/dataset/tabarena-GiveMeSomeCredit.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow10-out-3e3872ba/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow11-out-68e548cc/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow12-out-d10b1cf5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow13-out-5f47e008/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow14-out-232d2394/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow15-out-92a44276/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow16-out-f2fa81db/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow17-out-81f4ee5c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow18-out-0bc9f741/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow19-out-fc76c98a/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow10-in-7d948dd4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow11-in-10f82486/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow12-in-69659c47/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow13-in-c3ba384b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow14-in-b10a0299/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow15-in-858a31ff/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow16-in-7b31d0d8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow17-in-e0492cf1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow18-in-8179f6a5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow19-in-c32b3f0b/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow0-out-698a0ced/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae_bal-shadow0-in-46b0995b/default-44136fa3.csv
