synthesizer: ctgan
dataset: config/dataset/tabarena-GiveMeSomeCredit.yaml
downsample_balanced: true
canary_index: 100
include_canary: true
reference_size: 10026
reference_seed: 1
sample_size: 4010
sample_seed: 10
