synthesizer: original
dataset: config/dataset/tabarena-GiveMeSomeCredit.yaml
downsample_balanced: true
canary_index: 101
include_canary: true
reference_size: 10026
reference_seed: 21
sample_size: 4010
sample_seed: 30
