dataset: config/dataset/tabarena-GiveMeSomeCredit.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow10-out-2328a58d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow11-out-6c0c5b4a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow12-out-bd5b7991/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow13-out-d9a9c789/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow14-out-f3df8a4f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow15-out-7250d617/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow16-out-1a90d92a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow17-out-c7110997/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow18-out-d7712eca/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow19-out-16cc8395/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow10-in-dc4d38fa/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow11-in-4ed51a4e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow12-in-209c81d4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow13-in-9a729a54/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow14-in-dbf39bfe/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow15-in-41e022fa/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow16-in-2897628a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow17-in-2c313833/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow18-in-97ef6ddc/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow19-in-047f6ddb/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow0-out-18c93a2c/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_tvae_bal-shadow0-in-46956a21/default-44136fa3.csv
