dataset: config/dataset/adult.yaml
model: xgboost
target_metric: balanced_accuracy
train_override_df: /home/shared/ppsdg-data/train_and_gen/AD_0dp_ctgan_bigclip-53db90a3/default-44136fa3.csv
model_params: {}
train_params: {}
eval_params: {}
data_params: {}
metrics:
- balanced_accuracy
