dataset: config/dataset/tabarena-Bank_Customer_Churn.yaml
model: xgboost
target_metric: balanced_accuracy
train_override_df: /home/shared/ppsdg-data/train_and_gen/BC_5.0dp_ctgan_wgan_bal-680173aa/default-44136fa3.csv
model_params: {}
train_params: {}
eval_params: {}
data_params: {}
metrics:
- balanced_accuracy
