train_models:
- - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow10-out-bead37db/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow11-out-18bb3912/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow12-out-1b51f0f8/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow13-out-005edb4d/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow14-out-0925f6d5/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow15-out-594a319b/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow16-out-738cf970/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow17-out-57603d99/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow18-out-053b5687/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow19-out-a1fc5aa4/model.joblib
- - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow10-in-6ff3810b/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow11-in-03156e09/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow12-in-1163fe70/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow13-in-b53e2a90/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow14-in-d65e04dd/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow15-in-aa900113/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow16-in-d2f36621/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow17-in-2d2972d9/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow18-in-f9e300b1/model.joblib
  - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow19-in-b3f6ee2e/model.joblib
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow0-out-640906dd/model.joblib
- - /home/shared/ppsdg-data/train_and_gen/BM_dp0.1_ctgan-shadow0-in-b2e56934/model.joblib
