dataset: config/dataset/adult.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow10-out-958574ab/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow11-out-bdb5a56a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow12-out-51569735/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow13-out-00efe0a8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow14-out-40b72af9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow15-out-abb74f9e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow16-out-aec9def5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow17-out-5229ea59/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow18-out-80521274/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow19-out-b6afa9b8/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow10-in-5ccf0fea/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow11-in-b8d98c80/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow12-in-4c1325e7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow13-in-05d9c6f8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow14-in-3f7a3cfd/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow15-in-5fd0eb76/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow16-in-b4593454/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow17-in-b849c049/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow18-in-5a5831bf/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow19-in-11ad6cc0/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow0-out-2b54dcc8/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/AD_ctgan-shadow0-in-d05762b9/default-44136fa3.csv
