synthesizer: iter_tvae
dataset: config/dataset/adult.yaml
synthesizer_params:
  epsilon: 10.0
canary_index: 100
include_canary: true
reference_size: 24421
reference_seed: 2
sample_size: 9768
sample_seed: 26
