dataset: config/dataset/adult.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow10-out-10a5c1c3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow11-out-1201b413/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow12-out-5556f58f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow13-out-96b7ee2d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow14-out-8f257be2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow15-out-7b6f1eb3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow16-out-95caa0bc/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow17-out-dedf193c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow18-out-0ed85a1c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow19-out-c6ce8bf1/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow10-in-191452dd/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow11-in-49149006/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow12-in-d7a0cbce/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow13-in-8469afad/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow14-in-8ca7791c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow15-in-543d9169/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow16-in-09431df2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow17-in-145949c1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow18-in-1fb93396/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow19-in-b992dafd/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow0-out-ee3068bf/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/AD_tvae-shadow0-in-2920c543/default-44136fa3.csv
