dataset: config/dataset/tabarena-Bank_Customer_Churn.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow10-out-cf7f0de7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow11-out-856e618c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow12-out-e41730a2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow13-out-838233c2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow14-out-6b623329/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow15-out-0f71310a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow16-out-a6619179/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow17-out-a7a811fb/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow18-out-f5c6281e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow19-out-97f6d99e/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow10-in-d5a7f718/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow11-in-43cdff39/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow12-in-02a5deaf/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow13-in-53416f29/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow14-in-b2d090e9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow15-in-ad43a4c5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow16-in-9c804942/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow17-in-f3652843/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow18-in-47fbcbb2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow19-in-85b86f28/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow0-out-14cb5e0b/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_0.1dp_ctgan_wgan-shadow0-in-ee8af83b/default-44136fa3.csv
