dataset: config/dataset/tabarena-Bank_Customer_Churn.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow10-out-a01847ce/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow11-out-04e7140e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow12-out-6c10db66/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow13-out-f5c9b563/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow14-out-184182f9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow15-out-850ddcc7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow16-out-a04434fa/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow17-out-cacec570/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow18-out-f1ce2e5a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow19-out-1ec335af/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow10-in-8ea2c029/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow11-in-7c1b6731/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow12-in-de1cf28a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow13-in-c6a93d68/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow14-in-b5b533e5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow15-in-c23b2d2d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow16-in-4d95399e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow17-in-6f0db20f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow18-in-bb394d89/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow19-in-5138f15d/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow0-out-f321bdec/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_0dp_tvae-shadow0-in-e2d227bb/default-44136fa3.csv
