dataset: config/dataset/tabarena-Bank_Customer_Churn.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow10-out-a94d8d84/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow11-out-7e4b86ef/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow12-out-994b7912/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow13-out-443a8c98/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow14-out-193bb099/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow15-out-28e146cb/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow16-out-776cee5a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow17-out-58d4a394/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow18-out-9123817e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow19-out-ebeda540/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow10-in-4698097f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow11-in-5b29168d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow12-in-4c2cb933/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow13-in-bb795301/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow14-in-87ff2974/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow15-in-dd85dc39/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow16-in-95820c61/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow17-in-b9aaf72d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow18-in-42d2c2db/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow19-in-9d157035/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow0-out-3fb02f3b/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_1.0dp_tvae-shadow0-in-d3d412a0/default-44136fa3.csv
