synthesizer: iter_dp_ctgan
dataset: config/dataset/tabarena-Bank_Customer_Churn.yaml
synthesizer_params:
  epsilon: 5.0
canary_index: 100
include_canary: true
reference_size: 5000
reference_seed: 2
sample_size: 2000
sample_seed: 25
