dataset: config/dataset/tabarena-Bank_Customer_Churn.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow10-out-c96c811a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow11-out-a4d6a2db/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow12-out-20936531/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow13-out-c286a706/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow14-out-973fc78d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow15-out-c6f7e836/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow16-out-d133653b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow17-out-2766a74f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow18-out-bd4962ae/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow19-out-57dcea4d/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow10-in-ff28efe0/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow11-in-ed0ebf08/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow12-in-f4d13b26/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow13-in-fb02db2e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow14-in-9b5618f4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow15-in-fc3cd58c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow16-in-86ad11c8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow17-in-3e5dbd6f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow18-in-4096f1a8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow19-in-9f5d6135/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow0-out-0730d150/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BC_tvae-shadow0-in-7d12685b/default-44136fa3.csv
