dataset: config/dataset/tabarena-bank-marketing.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow10-out-05fd958b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow11-out-4e0a89cf/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow12-out-eda4e32c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow13-out-57956152/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow14-out-bc24d805/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow15-out-f95f246c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow16-out-1bd926bd/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow17-out-2b68d44c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow18-out-7cfab6ef/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow19-out-72f0fb89/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow10-in-225a8770/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow11-in-61ade1b6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow12-in-4074e808/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow13-in-1e166653/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow14-in-67b1e19b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow15-in-daba5665/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow16-in-e17ec835/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow17-in-2daf50de/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow18-in-d6212369/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow19-in-d735d2c0/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow0-out-15c3b3e4/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_ctgan_wgan-shadow0-in-9bb0c614/default-44136fa3.csv
