dataset: config/dataset/tabarena-bank-marketing.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow10-out-ba2902d3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow11-out-67e5095f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow12-out-70b37d20/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow13-out-45dd0b9a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow14-out-c580ac0e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow15-out-ceb20f21/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow16-out-73732add/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow17-out-a25965b2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow18-out-bbf0282d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow19-out-0bbfdd54/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow10-in-bc2720b6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow11-in-48929f7c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow12-in-1a9916bd/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow13-in-960dfe66/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow14-in-016191b3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow15-in-e30c1b09/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow16-in-c760b6dd/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow17-in-1ee02944/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow18-in-25b32ee1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow19-in-267fec3c/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow0-out-491e4ebf/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BM_0.1dp_tvae-shadow0-in-ed1fb888/default-44136fa3.csv
