synthesizer: dp_tvae
synthesizer_params:
  epsilon: 5.0
  delta: 1.0e-05
  max_grad_norm: 1.0
dataset: config/dataset/tabarena-bank-marketing.yaml
canary_index: 100
include_canary: true
reference_size: 22605
reference_seed: 2
sample_size: 9042
sample_seed: 24
