dataset: config/dataset/tabarena-bank-marketing.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow10-out-e1aded62/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow11-out-c7fe2041/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow12-out-4d920672/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow13-out-29963495/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow14-out-0850d077/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow15-out-b87ec749/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow16-out-823e8b17/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow17-out-13d32567/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow18-out-77b7b0a0/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow19-out-5767cda1/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow10-in-c9b3195c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow11-in-394c9039/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow12-in-43509206/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow13-in-7b76dfd2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow14-in-e9bf2f0c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow15-in-0e050342/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow16-in-180c5801/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow17-in-8c1fae1c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow18-in-5402e85e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow19-in-987b9ccb/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow0-out-ec1451bf/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BM_iter_10dp_tvae-shadow0-in-07ea061d/default-44136fa3.csv
