dataset: config/dataset/tabarena-bank-marketing.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow10-out-f574b37c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow11-out-f37ff2f1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow12-out-4ca6009b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow13-out-1e541fd5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow14-out-b2eb5a06/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow15-out-d90a0255/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow16-out-9e8528d9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow17-out-f50ac9a2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow18-out-bd9f140a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow19-out-f49f1045/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow10-in-fbca5514/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow11-in-ea8aa6e9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow12-in-2d608de7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow13-in-7baca481/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow14-in-4d389d5a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow15-in-cd9a2a63/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow16-in-b2f707a7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow17-in-8a787ac6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow18-in-c7441689/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow19-in-6957117d/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow0-out-28a41bf8/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/BM_tabdiff-shadow0-in-268fb92d/default-44136fa3.csv
