dataset: config/dataset/tabarena-credit_card_clients_default.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow10-out-5ac484c3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow11-out-8c26eeb6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow12-out-6fc441f1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow13-out-48153b39/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow14-out-9a493e66/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow15-out-79fc1371/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow16-out-35ff6f83/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow17-out-6bd4d1c9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow18-out-7ad8f0df/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow19-out-66abd9be/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow10-in-28e9d88c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow11-in-0d38a090/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow12-in-d9881f0e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow13-in-69d30739/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow14-in-345352da/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow15-in-791e86e3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow16-in-dce2ddba/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow17-in-f9f15c9f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow18-in-93bbd6ef/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow19-in-715bbac2/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow0-out-b61bba56/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CC_0.1dp_tvae-shadow0-in-7f778912/default-44136fa3.csv
