dataset: config/dataset/tabarena-credit_card_clients_default.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow10-out-796fb057/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow11-out-b7f12b8b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow12-out-6d8f55b9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow13-out-ac09296f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow14-out-581ec1a9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow15-out-9a4ce8f4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow16-out-8f579d4b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow17-out-29862df2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow18-out-af9a755f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow19-out-c0c9a8c1/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow10-in-c5368fc6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow11-in-70cd32cc/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow12-in-5928cbaa/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow13-in-f7fb7a56/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow14-in-053c608e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow15-in-f848ca3d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow16-in-67d6ec3f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow17-in-6b002c9d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow18-in-c90ec006/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow19-in-8ce6b49d/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow0-out-430934f3/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CC_1.0dp_ctgan_wgan-shadow0-in-cd64ca76/default-44136fa3.csv
