dataset: config/dataset/tabarena-credit_card_clients_default.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow10-out-6c45b573/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow11-out-0e1f4e1f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow12-out-04f9bea3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow13-out-1f2e231d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow14-out-5b8d0027/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow15-out-b82949c0/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow16-out-bb55900c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow17-out-4303e61f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow18-out-3e49e906/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow19-out-a2eab610/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow10-in-cf76ebd6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow11-in-ba3c386f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow12-in-8cecdff5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow13-in-51d406a8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow14-in-099c3cd0/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow15-in-00cf8724/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow16-in-5fa5aee2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow17-in-53ae1979/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow18-in-e4896bbd/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow19-in-2c677fd8/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow0-out-092a351a/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_ctgan_wgan-shadow0-in-a3b76a2a/default-44136fa3.csv
