dataset: config/dataset/tabarena-credit_card_clients_default.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow10-out-4dffde82/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow11-out-d6b8bb98/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow12-out-1f4407ba/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow13-out-59c5251b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow14-out-3b914af3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow15-out-b905d6cb/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow16-out-03a847eb/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow17-out-403035cf/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow18-out-ee8698c2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow19-out-dc480a13/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow10-in-81e3e932/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow11-in-e677cb2f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow12-in-7ea8d126/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow13-in-9730051f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow14-in-8ce22194/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow15-in-672d5847/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow16-in-132cfdba/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow17-in-0f277c72/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow18-in-7e68cfdd/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow19-in-797ff2e7/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow0-out-18fb142d/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CC_5.0dp_tvae-shadow0-in-9f06a4dc/default-44136fa3.csv
