dataset: config/dataset/tabarena-credit_card_clients_default.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow10-out-8da349b8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow11-out-b8753274/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow12-out-2dd114d1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow13-out-0875a6b5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow14-out-b6fbaa22/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow15-out-29121b01/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow16-out-80ca3c4a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow17-out-c60f811c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow18-out-5c150fef/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow19-out-43f321ab/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow10-in-4dfcdef3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow11-in-f1b79552/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow12-in-123d38b8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow13-in-b6179e44/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow14-in-cf7bc792/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow15-in-34a4d490/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow16-in-6d2ce230/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow17-in-2ff9fc7a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow18-in-d92bb4cb/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow19-in-9375f975/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow0-out-b977a727/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CC_original-shadow0-in-48c72283/default-44136fa3.csv
