dataset: config/dataset/tabarena-credit-g.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow10-out-d2b6c4ce/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow11-out-e37fc2c9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow12-out-286e45a9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow13-out-61eb3cd7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow14-out-b0fd00c4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow15-out-809aa3e9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow16-out-84100303/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow17-out-28dec19e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow18-out-67508f2d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow19-out-eaf984b3/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow10-in-5cfe334d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow11-in-c5c9ead2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow12-in-66307983/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow13-in-caa5ae8e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow14-in-5be39314/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow15-in-94f0e79f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow16-in-04c68b20/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow17-in-c8a7ff66/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow18-in-3f7bab81/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow19-in-429b8a7d/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow0-out-9722ddbb/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_0dp_ctgan_wgan-shadow0-in-67c1dfcd/default-44136fa3.csv
