dataset: config/dataset/tabarena-credit-g.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow10-out-2795d58b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow11-out-bcaa60e5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow12-out-7b776189/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow13-out-a0df66e5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow14-out-dd6a931a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow15-out-3e0d97cf/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow16-out-9266026f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow17-out-4364d789/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow18-out-4fab86a2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow19-out-92628e67/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow10-in-ff2c9f78/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow11-in-f46d54c3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow12-in-456cff71/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow13-in-0223ded3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow14-in-e26afae1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow15-in-96639050/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow16-in-4914d998/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow17-in-2a68989c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow18-in-adb017d0/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow19-in-07609a40/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow0-out-e25622ee/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_tvae-shadow0-in-a30be41e/default-44136fa3.csv
