synthesizer: dp_ctgan
synthesizer_params:
  epsilon: 0
  delta: 1.0e-05
  max_grad_norm: 1.0
  use_bce_loss: false
dataset: config/dataset/tabarena-credit-g.yaml
canary_index: 100
include_canary: true
reference_size: 500
reference_seed: 2
sample_size: 200
sample_seed: 26
