dataset: config/dataset/tabarena-credit-g.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow10-out-337ff36c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow11-out-a0ff2f65/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow12-out-56c5a7d3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow13-out-6e3b4251/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow14-out-f775fd9d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow15-out-07ecd7b9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow16-out-677580ba/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow17-out-05ccf9c1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow18-out-bc1289ac/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow19-out-abb01a85/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow10-in-afdd797f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow11-in-35a077d4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow12-in-744a0d6d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow13-in-80e2306e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow14-in-3fe55d55/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow15-in-175f7c68/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow16-in-62cd9a34/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow17-in-950ae7ae/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow18-in-a03dec67/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow19-in-d21e225c/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow0-out-9c3d2c55/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_0.1dp_ctgan_wgan-shadow0-in-d6c1a67d/default-44136fa3.csv
