dataset: config/dataset/tabarena-credit-g.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow10-out-b85c5291/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow11-out-1576f999/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow12-out-45f1f517/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow13-out-c210be1c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow14-out-3ef8ea4c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow15-out-9ef8aa0b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow16-out-3f448c18/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow17-out-b393f84e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow18-out-d9b8a8f6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow19-out-905f00d4/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow10-in-c8c8e5b4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow11-in-3d1d7078/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow12-in-f9f0e237/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow13-in-b45daa0f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow14-in-cd043eed/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow15-in-9a5351b7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow16-in-504ccab5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow17-in-b2a6a065/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow18-in-b982b753/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow19-in-785f7505/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow0-out-8966a89b/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_1.0dp_ctgan_wgan-shadow0-in-75847087/default-44136fa3.csv
