dataset: config/dataset/tabarena-credit-g.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow10-out-de2001ee/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow11-out-8dfd6354/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow12-out-752a837a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow13-out-f5d63638/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow14-out-438b7990/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow15-out-f9af5664/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow16-out-8b231d0d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow17-out-22b0c38b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow18-out-8d9d73a8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow19-out-414d59d5/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow10-in-8de81786/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow11-in-8962936d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow12-in-2382d630/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow13-in-932da4a9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow14-in-fe77ebcf/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow15-in-28f41ced/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow16-in-22968d71/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow17-in-7e55381e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow18-in-e01c63cb/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow19-in-66c81176/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow0-out-71127d49/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_tvae-shadow0-in-de028bd4/default-44136fa3.csv
