dataset: config/dataset/tabarena-credit-g.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow10-out-253b4404/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow11-out-286bd706/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow12-out-1332fe66/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow13-out-aa46d2b6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow14-out-ac136fd8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow15-out-d5e1f58e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow16-out-46e5a048/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow17-out-8ac39b97/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow18-out-aa3fd66e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow19-out-67877add/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow10-in-28e868c8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow11-in-02085112/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow12-in-f7552fbb/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow13-in-2ff7dede/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow14-in-256a29e6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow15-in-047b58b3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow16-in-b2f5b235/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow17-in-8bdfa2b9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow18-in-ebdae633/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow19-in-8c0c24f5/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow0-out-6b19add8/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_5.0dp_ctgan_wgan-shadow0-in-f0815d6b/default-44136fa3.csv
