dataset: config/dataset/tabarena-credit-g.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow10-out-a89f1aee/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow11-out-0213fb79/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow12-out-244c4a76/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow13-out-48313243/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow14-out-49283cda/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow15-out-79d456f9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow16-out-5e05df3e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow17-out-59243ac7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow18-out-709b8a26/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow19-out-853e4881/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow10-in-ac137d98/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow11-in-7137619d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow12-in-9ab883d7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow13-in-f794e85e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow14-in-19cde6a9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow15-in-f3f68b52/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow16-in-af72f13b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow17-in-f27e20a5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow18-in-fff3f1b8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow19-in-7a5510cd/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow0-out-ca8ff9ed/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_ctgan-shadow0-in-48396c9a/default-44136fa3.csv
