dataset: config/dataset/tabarena-credit-g.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow10-out-0d5e1e71/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow11-out-59f348f8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow12-out-866e7340/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow13-out-46287938/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow14-out-85221baa/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow15-out-b861c139/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow16-out-865a5216/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow17-out-0be8d401/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow18-out-e07e8af4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow19-out-7dec29e3/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow10-in-5b01a770/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow11-in-5f27dc7f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow12-in-def5d6fb/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow13-in-7f401f8a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow14-in-7d4323be/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow15-in-a7fdb332/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow16-in-ecb0ab4c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow17-in-056803d6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow18-in-920af3d8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow19-in-c8bcfeb9/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow0-out-8e24389e/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/CR_gaussian-shadow0-in-94e7288b/default-44136fa3.csv
