synthesizer: iter_tvae
dataset: config/dataset/tabarena-credit-g.yaml
synthesizer_params:
  epsilon: 5.0
canary_index: 100
include_canary: false
reference_size: 500
reference_seed: 2
sample_size: 200
sample_seed: 29
