dataset: config/dataset/tabarena-GiveMeSomeCredit.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow10-out-30ed00cd/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow11-out-9b5ff428/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow12-out-b9967789/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow13-out-4b97dd83/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow14-out-e99c52d6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow15-out-b9995507/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow16-out-e4e52b5f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow17-out-3ca73637/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow18-out-a1bb11f4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow19-out-b928590c/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow10-in-d41e2d01/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow11-in-5eb96e7f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow12-in-f22ea921/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow13-in-08cac157/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow14-in-dd97d541/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow15-in-d53d46ed/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow16-in-52cadd56/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow17-in-fe51301b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow18-in-1bec7dd5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow19-in-644a644e/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow0-out-1098a4e6/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_0dp_tvae-shadow0-in-93664410/default-44136fa3.csv
