dataset: config/dataset/tabarena-GiveMeSomeCredit.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow10-out-757cebff/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow11-out-3764283d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow12-out-1d806790/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow13-out-ab0c5273/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow14-out-c37f6fa8/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow15-out-5071e28d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow16-out-3f544981/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow17-out-8123b917/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow18-out-b0236a5d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow19-out-adaafe85/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow10-in-98790792/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow11-in-ddc2f892/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow12-in-eed366aa/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow13-in-5b388ebb/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow14-in-108b316c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow15-in-1a839a7c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow16-in-bd05345c/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow17-in-e3adec2f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow18-in-b6f31b6d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow19-in-a74e6df4/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow0-out-63f56a13/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_1.0dp_tvae-shadow0-in-7ee2c4cb/default-44136fa3.csv
