dataset: config/dataset/tabarena-GiveMeSomeCredit.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow10-out-ba19179e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow11-out-834e41cb/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow12-out-0ce7787d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow13-out-dcef0d04/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow14-out-3f13f9a5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow15-out-33ce6d89/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow16-out-82f2bbc0/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow17-out-4d4720fc/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow18-out-ec0d0fd5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow19-out-5fe31813/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow10-in-76d08032/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow11-in-37188e42/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow12-in-b5cfd3d2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow13-in-cf628485/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow14-in-8211a366/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow15-in-12261d6f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow16-in-e813a30f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow17-in-d5d76534/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow18-in-8e8a0d25/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow19-in-25800cef/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow0-out-3f7931b6/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_5.0dp_tvae-shadow0-in-02aa7b0e/default-44136fa3.csv
