dataset: config/dataset/tabarena-GiveMeSomeCredit.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow10-out-4cbed0b3/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow11-out-1882e060/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow12-out-7e6f2ade/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow13-out-0e84e037/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow14-out-c158bd8f/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow15-out-9ceee6c1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow16-out-ddab109d/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow17-out-5dfca596/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow18-out-8f9f72a5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow19-out-8fc0ef89/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow10-in-dba365d6/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow11-in-c1308ea5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow12-in-09dcf466/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow13-in-b0cd5f16/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow14-in-7f84db4a/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow15-in-bc826ef7/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow16-in-78e15566/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow17-in-ea16ef79/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow18-in-3d5acd32/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow19-in-2712e00a/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow0-out-a1ea7338/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_original-shadow0-in-24a0fb28/default-44136fa3.csv
