dataset: config/dataset/tabarena-GiveMeSomeCredit.yaml
train_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow10-out-3c259426/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow11-out-6953e4f5/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow12-out-d74fe7f9/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow13-out-9b059b61/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow14-out-fe0c4cc1/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow15-out-d7e14357/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow16-out-a1cfc4e4/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow17-out-0a5bb543/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow18-out-3fb3c9a0/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow19-out-94e47d8d/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow10-in-b4eccb84/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow11-in-ee547648/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow12-in-76e53e6e/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow13-in-2e1594c2/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow14-in-7e894a8b/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow15-in-1bb4e315/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow16-in-fa14f573/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow17-in-f1d8e298/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow18-in-73bcf458/default-44136fa3.csv
  - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow19-in-863e5b43/default-44136fa3.csv
test_models:
- - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow0-out-d97ecafc/default-44136fa3.csv
- - /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-shadow0-in-36b67727/default-44136fa3.csv
