synthesizer: tabdiff
dataset: config/dataset/tabarena-GiveMeSomeCredit.yaml
train_params:
  steps: 300
canary_index: 100
include_canary: true
reference_size: 75000
reference_seed: 1
sample_size: 30000
sample_seed: 10
