dataset: config/dataset/tabarena-GiveMeSomeCredit.yaml
synthetic_data: /home/shared/ppsdg-data/train_and_gen/GM_tabdiff-80f78bb3/default-44136fa3.csv
metrics:
  - dcr_val_to_real_vs_synth
  - dcr_baseline
  - dcr_overfit
